package com.scifi.markirapp.utils

import com.scifi.markirapp.data.model.ParkingSlot

object DummyData {
    val allSlots = listOf(
        ParkingSlot("A01", true, 1),
        ParkingSlot("A02", false, 1),
        ParkingSlot("A03", true, 1),
        ParkingSlot("A04", true, 1),
        ParkingSlot("A05", false, 1),
        ParkingSlot("A06", true, 1),
        ParkingSlot("A07", false, 1),
        ParkingSlot("A08", true, 1),
        ParkingSlot("A09", true, 1),
        ParkingSlot("A10", false, 1),
        ParkingSlot("A11", true, 1),
        ParkingSlot("A12", true, 1),
        ParkingSlot("A13", false, 1),
        ParkingSlot("A14", true, 1),
        ParkingSlot("A15", false, 1),
        ParkingSlot("A16", true, 1),

        ParkingSlot("B01", true, 1),
        ParkingSlot("B02", false, 1),
        ParkingSlot("B03", false, 1),
        ParkingSlot("B04", true, 1),
        ParkingSlot("B05", true, 1),
        ParkingSlot("B06", false, 1),
        ParkingSlot("B07", true, 1),
        ParkingSlot("B08", false, 1),
        ParkingSlot("B09", true, 1),
        ParkingSlot("B10", false, 1),
        ParkingSlot("B11", true, 1),
        ParkingSlot("B12", true, 1),
        ParkingSlot("B13", false, 1),
        ParkingSlot("B14", true, 1),
        ParkingSlot("B15", false, 1),
        ParkingSlot("B16", true, 1),

        ParkingSlot("C01", false, 2),
        ParkingSlot("C02", true, 2),
        ParkingSlot("C03", false, 2),
        ParkingSlot("C04", true, 2),
        ParkingSlot("C05", true, 2),
        ParkingSlot("C06", false, 2),
        ParkingSlot("C07", true, 2),
        ParkingSlot("C08", false, 2),
        ParkingSlot("C09", true, 2),
        ParkingSlot("C10", false, 2),
        ParkingSlot("C11", true, 2),
        ParkingSlot("C12", true, 2),
        ParkingSlot("C13", false, 2),
        ParkingSlot("C14", true, 2),
        ParkingSlot("C15", false, 2),
        ParkingSlot("C16", true, 2),

        ParkingSlot("D01", true, 2),
        ParkingSlot("D02", false, 2),
        ParkingSlot("D03", true, 2),
        ParkingSlot("D04", false, 2),
        ParkingSlot("D05", true, 2),
        ParkingSlot("D06", false, 2),
        ParkingSlot("D07", true, 2),
        ParkingSlot("D08", false, 2),
        ParkingSlot("D09", true, 2),
        ParkingSlot("D10", false, 2),
        ParkingSlot("D11", true, 2),
        ParkingSlot("D12", true, 2),
        ParkingSlot("D13", false, 2),
        ParkingSlot("D14", true, 2),
        ParkingSlot("D15", false, 2),
        ParkingSlot("D16", true, 2)
    )

}